server:
  port: 9000
cool:
  zhouxin:
    datasource:
      db1:
        url: jdbc:mysql://localhost:3306/zx?serverTimezone=GMT%2B0800&useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=UTF-8&useSSL=false&nullCatalogMeansCurrent=true
        username: root
        password: 123456
      db2:
        url: jdbc:mysql://localhost:3306/zx1?serverTimezone=GMT%2B0800&useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=UTF-8&useSSL=false&nullCatalogMeansCurrent=true
        username: root
        password: 123456
spring:
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update
